Flaber started at:<class 'datetime.datetime'>
Labeling conn.log file: ../../../../captures/iot-pcaps/CTU-IoT-Malware-Capture-49-1/bro/conn.log with 5410562 lines 
Exception in labeler function: 'resp_bytes' 
 Exception at row: {'Field': 'resp_bytes', 'bro field number': '9', 'Data': '5000', 'Comparator': 'gt', 'Label': 'FileDownload', 'type': 'Malicious', 'connector': '-'} 
 Exception at flow {'ts': '1551409817.668471', 'uid': 'Ctc2If2AEpNehSWL2a', 'id.orig_h': '192.168.1.193', 'id.orig_p': 30535, 'id.resp_h': '217.48.18.213', 'id.resp_p': 8081, 'proto': 'tcp', 'service': '', 'conn_state': 'S0', 'local_orig': False, 'local_resp': False, 'missed_bytes': 0, 'history': 'S', 'orig_pkts': 1, 'orig_ip_bytes': 40, 'resp_pkts': 0, 'resp_ip_bytes': 0, 'tunnel_parents': ''} 
 Flaber finished at:03/12/19 11:22:49
